# Testy nezávislosti

In [2]:
import numpy as np
import scipy.stats as st

## Příklad 6.1

In [1]:
# data
x = [0.055 , 0.068 , 0.102 , 0.105 , 0.118 , 0.160 , 0.178 , 0.203 , 0.260 , 0.274, 0.289 , 0.291 , 0.346 , 0.358 , 0.366 , 0.472 , 0.588 , 0.617 , 0.721 , 0.932]
n = len(x)

In [3]:
# četnosti
k = 4 #počet binů
Ni, edges = np.histogram(x, bins = k, range = (0,1), density = None)
n = np.sum(Ni)
print("Edges =" ,edges)
print("n = ", n, ", Ni = ", Ni, sep="")


Edges = [0.   0.25 0.5  0.75 1.  ]
n = 20, Ni = [8 8 3 1]


In [6]:
# teoretické četnosti
k = 4
pi = np.ones(k) * 1/k
npi = n * pi
print("pi =", pi)
print("npi =", npi)

pi = [0.25 0.25 0.25 0.25]
npi = [5. 5. 5. 5.]


In [7]:
# testová statistika
Chi2 = sum((Ni - npi)*(Ni - npi)/npi)
print("Chi2 =", Chi2)
# kritická hodnota
alpha = 0.05
df = k-1
chi2 = st.chi2.isf(alpha,df)
print("chi2 =", chi2)

Chi2 = 7.6000000000000005
chi2 = 7.814727903251178


In [8]:
# p-hodnota
p = st.chi2.sf(Chi2,df) # = 1-st.chi2.cdf(Chi2,df)
print("p =", p)

p = 0.05504393637887805


In [9]:
# pomocí funkce
st.chisquare(Ni,npi)

Power_divergenceResult(statistic=7.6000000000000005, pvalue=0.05504393637887805)

## Příklad 6.2

In [10]:
# skutečné četnosti
Nij = np.matrix([[1, 11, 7, 21],[0, 8, 23, 29]])
n = np.sum(Nij)
print("Nij =\n", Nij)
print("n =", n)

Nij =
 [[ 1 11  7 21]
 [ 0  8 23 29]]
n = 100


In [11]:
# odhady marginál
pi_ = np.sum(Nij, axis = 1)/n
p_j = np.sum(Nij, axis = 0)/n
print("pi_ =\n", pi_)
print("p_j =\n", p_j)

pi_ =
 [[0.4]
 [0.6]]
p_j =
 [[0.01 0.19 0.3  0.5 ]]


In [12]:
# teoretické četnosti
pipj = np.matmul(pi_,p_j)
print("pipj =\n",pipj)
npipj = n * pipj
print("npipj =\n",npipj)

pipj =
 [[0.004 0.076 0.12  0.2  ]
 [0.006 0.114 0.18  0.3  ]]
npipj =
 [[ 0.4  7.6 12.  20. ]
 [ 0.6 11.4 18.  30. ]]


In [13]:
# nutné sloučit 1. a 2. sloupec
cc12 = np.sum(Nij[:,:2], axis = 1)
cc34 = Nij[:,2:]
Nij = np.append(cc12, cc34, axis = 1)
n = np.sum(Nij)
print("Nij =\n", Nij)
print("n =", n)

Nij =
 [[12  7 21]
 [ 8 23 29]]
n = 100


In [14]:
# odhady marginál
pi_ = np.sum(Nij, axis = 1)/n
p_j = np.sum(Nij, axis = 0)/n
print("pi_ =\n", pi_)
print("p_j =\n", p_j)
# teoretické četnosti
pipj = np.matmul(pi_,p_j)
print("pipj =\n",pipj)
npipj = n * pipj
print("npipj =\n",npipj)

pi_ =
 [[0.4]
 [0.6]]
p_j =
 [[0.2 0.3 0.5]]
pipj =
 [[0.08 0.12 0.2 ]
 [0.12 0.18 0.3 ]]
npipj =
 [[ 8. 12. 20.]
 [12. 18. 30.]]


In [15]:
# testová statistika
Chi2 = np.sum(np.square(Nij - npipj)/npipj)
print("Chi2 =", Chi2)
# kritická hodnota
alpha = 0.05
df = (np.size(Nij,axis =0) - 1)*(np.size(Nij,axis =1) - 1)
print("df =",df)
chi2 = st.chi2.isf(alpha,df)
print("chi2 =", chi2)

Chi2 = 6.888888888888886
df = 2
chi2 = 5.991464547107983


In [16]:
# p-hodnota
p = st.chi2.sf(Chi2,df) # = 1-st.chi2.cdf(Chi2,df)
print("p =", p)

p = 0.031922491834895754


In [17]:
# pomocí funkce
Chi2, p, df, _ = st.chi2_contingency(Nij, correction = False)
print("Chi2 =", Chi2)
print("df =",df)
print("p =", p)

Chi2 = 6.888888888888889
df = 2
p = 0.031922491834895705
